spring:
  datasource:
    url: jdbc:mysql://hopper.proxy.rlwy.net:19252/railway
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret-key: ${JWT_SECRET}

server:
  port: ${PORT:8080}
